relationship_type = {
    'CHILD': 'CHILD',
    'SPOUSE': 'SPOUSE',
    'PARENT': 'PARENT',
    'SIBLING': 'SIBLING'
}

member_gender = {
    'MALE': 'MALE',
    'FEMALE': 'FEMALE',
    'N/A': 'N/A'
}


valid_actions = {
    'ADD_CHILD': 'ADD_CHILD',
    'GET_RELATIONSHIP': 'GET_RELATIONSHIP',
    'ADD_SPOUSE': 'ADD_SPOUSE',
}

output_messages = {
    'INVALID_ACTION': 'INVALID_ACTION',
    'INVALID_INPUT': 'INVALID_INPUT',
    'CHILD_ADDITION_SUCCEEDED': 'CHILD_ADDITION_SUCCEEDED',
    'PERSON_NOT_FOUND': 'PERSON_NOT_FOUND',
    'INVALID_GENDER': 'INVALID_GENDER',
    'INVALID_RELATIONSHIP_TYPE': 'INVALID_RELATIONSHIP_TYPE',
    'CHILD_ADDITION_FAILED': 'CHILD_ADDITION_FAILED',
    'RELATIONSHIP_UNSUPPORTED': 'RELATIONSHIP_UNSUPPORTED',
    'SUCCESS': 'SUCCESS',
    'SPOUSE_ADDITION_SUCCEEDED': 'SPOUSE_ADDITION_SUCCEEDED',
    'NO_RESULT': 'NO_RESULT'
}
